## BUNUS QUESTION

In [2]:
import numpy as np

## part a)

## multiplying 5x3 matrix by a 3x2 matrix

## we first create a 5x3 matrix and name it as A

In [6]:
A = np.array([[1,2,3],[2,0,3],[6,7,1],[2,1,6],[3,2,0]])
print(A)

[[1 2 3]
 [2 0 3]
 [6 7 1]
 [2 1 6]
 [3 2 0]]


## then we create another one of 3x2 matrix and name it as B

In [7]:
B = np.array([[0,2],[4,5],[1,9]])
print(B)

[[0 2]
 [4 5]
 [1 9]]


## now we are going to multiply our matrix A and B by using the method below

In [8]:
product = np.dot(A,B)
print(product)

[[11 39]
 [ 3 31]
 [29 56]
 [10 63]
 [ 8 16]]


## part b)

## creating a 3x3 identity matrix,here we are going to use the method below;

In [10]:
identity = np.array([[0,1,0],[1,0,1],[0,1,0]])
print(identity)

[[0 1 0]
 [1 0 1]
 [0 1 0]]


## part c)

## we are asked to create a vector ranging from 10 to 49, below are the method of creating ranging vector;

In [11]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## part d)

##  we are creating a null vector of size 10 using the method below;

In [12]:
vector_null = np.zeros(10)
print(vector_null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## e)

## we are asked to create a 3x3x3 array with random values,below is the method to use with it's output; 

In [22]:
from numpy import random
x = random.poisson(size=(3,3,3))
print(x)

[[[0 1 1]
  [1 1 2]
  [0 1 1]]

 [[0 0 1]
  [1 0 1]
  [1 1 1]]

 [[0 1 2]
  [2 2 0]
  [2 2 0]]]


## part f)

### to create a 5x5 matrix with values 1,2,3,4 just below the diagonal, here we use the method below;

In [26]:
matrix = np.zeros((5,5),dtype=int)
mattrix = np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## part g)

## normalising a 5x5 random matrix ,we use the following method below;


In [29]:
from numpy import  random
x = random.normal(size =(5,5))
print(x)

[[ 0.15488152  0.6457614   0.8707534  -1.22772191  0.32180602]
 [ 1.08850919 -1.07880514  0.25116933  0.31978676 -0.54662236]
 [-0.04361493 -0.2958405   0.49454431 -0.76065683 -0.85547971]
 [-1.97737131  0.72914718 -0.17244216  0.41590912 -0.64615908]
 [-1.0818065  -0.58171724 -1.65889586 -0.50050332  0.55494635]]


## part h)

## how to get dates of yesterday,today and tomorrow?
## below are the formula and methods;

In [34]:
today = np.datetime64('today','D')## this how we get dates of today
print(today)

2024-12-10


In [35]:
yesterday = today-np.timedelta64(1,'D')## to get for yesterday ,we subtract today from np.timedelta64
print(yesterday)

2024-12-09


In [36]:
tomorrow = today + np.timedelta64(1,'D')## to get fo tomorrow , we just add today to np.timedelta64
print(tomorrow)

2024-12-11


## part i)

## to find the indices of non-zero elements from [1,2,0,0,4,0].still we use numpy as np 

In [38]:
import numpy as np
x= np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(x)
print( non_zero_indices[0])


[0 1 4]
